"""更新 record_type table

Revision ID: 16037bdb6864
Revises: a1cde3270dcb
Create Date: 2023-06-06 04:30:40.944494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16037bdb6864'
down_revision = 'a1cde3270dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_type', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('current_price')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('current_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
