"""新增 record_type table

Revision ID: a1cde3270dcb
Revises: fd13c79f3eaf
Create Date: 2023-06-06 04:18:33.207949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cde3270dcb'
down_revision = 'fd13c79f3eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'record_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=30), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('current_price', sa.Float(), nullable=True),
        sa.Column('desc', sa.Text(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('record_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_type_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_type_name'))

    op.drop_table('record_type')
    # ### end Alembic commands ###
